SOURCE_DIR="media/SHUTTLE/kanji-quiz"
PYGAME_DIR="/userdata/roms/pygame"
IMAGE_DIR="$PYGAME_DIR/images"
GAME_DIR="$PYGAME_DIR/quiz"
mkdir -p "$GAME_DIR"
cp -r "$SOURCE_DIR/sets" "$GAME_DIR"
cp "$SOURCE_DIR/quiz.py" "$GAME_DIR/quiz.py"
cp "$SOURCE_DIR/main.py" "$GAME_DIR/kanji-quiz.pygame"
cp "$SOURCE_DIR/kanji.png" "$IMAGE_DIR/kanji-quiz.png"
