PYGAME_DIR="/Volumes/SHARE/roms/pygame/quiz"
IMAGE_DIR="/Volumes/SHARE/roms/pygame/images"
GAME_DIR="$PYGAME_DIR/quiz"
mkdir -p "$GAME_DIR"
cp -r sets "$GAME_DIR"
cp quiz.py "$GAME_DIR/quiz.py"
cp main.py "$GAME_DIR/kanji-quiz.pygame"
cp kanji.png "$IMAGE_DIR/kanji-quiz.png"
